POST http://localhost:5000/auth
Content-Type: application/json

{
    "email": "doe-ray-mi@gmail.com",
    "password": "Janeismyname"
}

###

GET http://localhost:5000/contact_form/entries
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZS1yYXktbWlAZ21haWwuY29tIiwiaWF0IjoxNjUwNTk0NzA5LCJleHAiOjE2NTA1OTU2MDl9.WeJC9P9-piayE-jznNhrmzWbqpEUsTsPnCpBlJZvaSg"